export const responseData = {
  responseStructure: {
    current_page: 1,
    data: [],
    from: 1,
    last_page: 6,
    per_page: 9,
    to: 9,
    total: 50,
  },
  responseDataSingleProduct: {
    id: "01M39VF4R8ABJ986G713ZGV78W",
    name: "Combination Pliers",
    description:
      "Versatile combination pliers designed for gripping, bending, and cutting wire with ease. Featuring chrome vanadium steel construction with induction-hardened cutting edges, these pliers deliver excellent grip and leverage for a wide range of tasks. The precision-machined jaws combine flat gripping surfaces with a pipe-grip section and integrated wire cutter for true multi-purpose functionality. Ergonomic bi-component handles reduce hand fatigue during extended use and provide a secure hold even with oily or gloved hands. The joint is precisely fitted to eliminate play and ensure smooth operation over thousands of cycles. Ideal for electricians, mechanics, and DIY enthusiasts tackling everyday projects around the workshop or job site.",
    price: 14.15,
    is_location_offer: false,
    is_rental: false,
    co2_rating: "D",
    in_stock: true,
    is_eco_friendly: false,
    product_image: {
      id: "01M39VF4QF8RXDMNKR5GJEJVHY",
      by_name: "Helinton Fantin",
      by_url: "https://unsplash.com/@fantin",
      source_name: "Unsplash",
      source_url: "https://unsplash.com/photos/W8BNwvOvW4M",
      file_name: "pliers01.avif",
      title: "Combination pliers",
    },
    category: {
      id: "01M39VF4Q31R4GG80ZF45JKPHN",
      name: "Pliers",
      slug: "pliers",
      parent_id: "01M39VF4PTE1E8G5KGY4MABGKT",
    },
    brand: {
      id: "01M39VF4CNTCZPW3VWQCP9WJ8R",
      name: "ForgeFlex Tools",
    },
    specs: [
      {
        id: "01M39VF52J00BHTQAX6PQ8E0SV",
        product_id: "01M39VF4R8ABJ986G713ZGV78W",
        spec_name: "Handle Material",
        spec_value: "Bi-component",
        spec_unit: null,
      },
      {
        id: "01M39VF52J00BHTQAX6PQ8E0SS",
        product_id: "01M39VF4R8ABJ986G713ZGV78W",
        spec_name: "Length",
        spec_value: "200",
        spec_unit: "mm",
      },
      {
        id: "01M39VF52J00BHTQAX6PQ8E0ST",
        product_id: "01M39VF4R8ABJ986G713ZGV78W",
        spec_name: "Material",
        spec_value: "Chrome Vanadium Steel",
        spec_unit: null,
      },
      {
        id: "01M39VF52J00BHTQAX6PQ8E0SW",
        product_id: "01M39VF4R8ABJ986G713ZGV78W",
        spec_name: "Warranty",
        spec_value: "2",
        spec_unit: "years",
      },
      {
        id: "01M39VF52J00BHTQAX6PQ8E0SR",
        product_id: "01M39VF4R8ABJ986G713ZGV78W",
        spec_name: "Weight",
        spec_value: "340",
        spec_unit: "g",
      },
    ],
  },
};
